### PR TITLE
cmd/gb-vendor: move copypath to vendor.Copypath, skip symlinks

### LINKED ISSUE #184: cmd/gb-vendor: copyfile does not handle invalid symlinks
`copyfile` pukes if it hits an invalid symlink.

Go does not support symlinks inside the source directory, and this example is from a test fixture, and we don't run tests inside `$PROJECT/vendor`. The simplest approach would be to skip symlinks.
```
copyfile(dst: /home/dfc/devel/juju/vendor/src/gopkg.in/juju/charm.v5/internal/test-charm-repo/series/format2/build/ignored, src: /tmp/gb-vendor-720588324/internal/test-charm-repo/series/format2/build/ignored)
FATAL command "fetch" failed: copyfile: open("/tmp/gb-vendor-720588324/internal/test-charm-repo/series/format2/hooks/symlink"): open /tmp/gb-vendor-720588324/internal/test-charm-repo/series/format2/hooks/symlink: no such file or directory
FATAL command "vendor" failed: exit status 1
```

### PR DESCRIPTION
**Pull request by davecheney**
Fixes #184 

Ignore symlinks in the src directory.

Also mutes debugging output from `copyfile`

### CODE REVIEW

**Comment by davecheney** [comment]
Test's for `copyfile`/`Copypath` could be improved.

File: cmd/gb-vendor/vendor/copy_test.go [hunk 1]
```diff
@@ -0,0 +1,20 @@
...
+import (
+	"os"
+	"path/filepath"
+	"runtime"
+	"testing"
+)
+
+func TestCopypathSkipsSymlinks(t *testing.T) {
+	if runtime.GOOS == "windows" {
+		t.Skip("no symlinks on windows y'all")
```
Comment (davidkaya) [inline cmd/gb-vendor/vendor/copy_test.go]: If I am not mistaken there are symlinks on Windows :))
