### PR TITLE
Vendor fetch fix #187

### LINKED ISSUE #187: gb vendor fetch should bail out earlier if the dep is already registered
```
% gb vendor fetch gopkg.in/mgo.v2/bson
Cloning into '/tmp/gb-vendor-667504155'...
remote: Counting objects: 2419, done.
remote: Compressing objects: 100% (28/28), done.
remote: Total 2419 (delta 9), reused 0 (delta 0), pack-reused 2391
Receiving objects: 100% (2419/2419), 5.58 MiB | 1.18 MiB/s, done.
Resolving deltas: 100% (1653/1653), done.
Checking connectivity... done.
FATAL command "fetch" failed: already registered
FATAL command "vendor" failed: exit status 1
```

### PR DESCRIPTION
**Pull request by davidkaya**
Fixes #187 

Fetch won't clone the repository if it already exists.

### CODE REVIEW

File: cmd/gb-vendor/fetch.go [hunk 1]
```diff
@@ -56,7 +56,11 @@ Flags:
 			return err
 		}
 
-		wc, err := repo.Checkout(branch, revision)
+		if m.HasDependencyWithUrl(repo.URL()) {
+			return fmt.Errorf("specified repository is already downloaded")
+		}
+
+		wc, err := repo.Checkout("", "")
```
Comment (davecheney) [inline cmd/gb-vendor/fetch.go]: checkout(branch, revision)

Comment (davidkaya) [inline cmd/gb-vendor/fetch.go]: Fixed, leftover from weird rebasing process, thus duplicated commits.

File: cmd/gb-vendor/fetch.go [hunk 2]
```diff
@@ -56,7 +56,11 @@ Flags:
 			return err
 		}
 
-		wc, err := repo.Checkout(branch, revision)
+		if m.HasDependencyWithUrl(repo.URL()) {
+			return fmt.Errorf("specified repository is already downloaded")
```
Comment (davecheney) [inline cmd/gb-vendor/fetch.go]: I think this needs more information, for example if we've vendored

example.org/foo/bar/baz

then example.org/foo/bar will be the url

so venforing example.org/foo/bar/quux

will fail, but the message is confusing because we haven't vendored this url before, but a sibling of it.

Comment (davidkaya) [inline cmd/gb-vendor/fetch.go]: Something like `fmt.Errorf("%s is already vendored from %s repository", path, repo.URL())` ?

Comment (davecheney) [inline cmd/gb-vendor/fetch.go]: What if you check that both d.URL and d.Path match.

Comment (davidkaya) [inline cmd/gb-vendor/fetch.go]: I am afraid I don't quite understand you :)

Comment (davecheney) [inline cmd/gb-vendor/fetch.go]: For some reason I cannot find these comments on github, which makes it hard
to understand the context.

Comment (davidkaya) [inline cmd/gb-vendor/fetch.go]: If you open the pull request, there is "Show outdated diff" next to the "davecheney commented on an outdated diff an hour ago".

**Comment by davidkaya** [comment]
@davecheney Dave what about this PR?

**Comment by davecheney** [comment]
@davidkaya sorry I wasn't making much sense last night. Here is the problem that I see with this patch
```
lucky(~/devel/juju) % gb vendor fetch gopkg.in/mgo.v2/bson                                                                                                      
Cloning into '/tmp/gb-vendor-715659076'...
remote: Counting objects: 2419, done.
remote: Compressing objects: 100% (28/28), done.
remote: Total 2419 (delta 9), reused 0 (delta 0), pack-reused 2391
Receiving objects: 100% (2419/2419), 5.58 MiB | 1.07 MiB/s, done.
Resolving deltas: 100% (1653/1653), done.
Checking connectivity... done.
lucky(~/devel/juju) % gb vendor fetch gopkg.in/mgo.v2
FATAL command "fetch" failed: specified repository is already downloaded
FATAL command "vendor" failed: exit status 1
```

**Comment by davidkaya** [comment]
Well that opens bigger issue. When I `gb vendor fetch gopkg.in/mgo.v2/bson --branch little_ponny` and then `gb vendor fetch gopkg.in/mgo.v2 --branch master` it will overwrite the bson, wouldn't it?

**Comment by davecheney** [comment]
Yes. This also needs to be fixed. For #187, if you check that dep.Url and
dep.Path match, that should be sufficient.

Please open a new bug for your previous comment, this is a serious problem.

**Comment by davidkaya** [comment]
Done, I hope it is ok no. Also created #198
